<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add key' => '',
    'Add torrent' => 'Torrent toevoegen',
    'Admin' => '',
    'Audit' => '',
    'Change avatar' => '',
    'Create Game' => '',
    'Created by' => '',
    'Created on' => '',
    'Cron' => '',
    'Delete' => '',
    'Delete key' => '',
    'Download' => 'Download',
    'Email' => '',
    'Games' => 'Spellen',
    'Gii' => '',
    'Home' => '',
    'If you do not have an account, you can' => 'Als je geen account hebt, dan',
    'If you forgot your password you can' => 'Bende gei nou dâ woord vergeten,',
    'Keys' => 'Keys',
    'Login' => 'Inloggen',
    'Logout' => 'Uitloggen',
    'Logs' => 'Logs',
    'Member since:' => 'Lid sinds:',
    'Modified on' => 'Aangepast op',
    'Not found!' => 'Niet gevonden!',
    'Password' => 'Wachtwoord',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Please fill out the following fields to signup:' => '',
    'Profile image of' => '',
    'Profiles' => 'Profielen',
    'Queue' => '',
    'Registrate' => 'Registreer',
    'Request password reset' => '',
    'Reset password' => 'Wijzig wachtwoord',
    'Save' => 'Opslaan',
    'Send' => 'Verstuur',
    'Signup' => 'Registreren',
    'Sorry we didn\'t it so it\'s your mistake' => 'Sorry wij maakte hem niet dus het moet jouw fout zijn!',
    'The above error occurred while the Web server was processing your request.' => '',
    'Torrents' => '',
    'Unable to find user for avatar update!' => '',
    'Unable to save Avatar!' => '',
    'Unable to save Game!' => '',
    'Unable to save GameKey!' => '',
    'Unable to save GameTorrent!' => '',
    'Unable to save TorrentDownload!' => '',
    'Unable to save torrent!' => '',
    'Unable to upload files!' => '',
    'Update' => 'Wijzig',
    'Username' => 'Gebruikersnaam',
    'Users' => 'Gebruikers',
    'View game' => 'Bekijk spel',
    'View profile of' => 'Bekijk profiel van',
    'View site of' => 'Bekijk site van',
    'create it' => 'maak die aan',
    'info' => 'info',
    'reset it' => 'herstel het',
    'view' => 'bekijk',
];
