<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cron' => '',
    'If you do not have an account, you can' => '',
    'If you forgot your password you can' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Queue' => '',
    'Request password reset' => '',
    'Reset password' => '',
    'The above error occurred while the Web server was processing your request.' => '',
    'Unable to save Game!' => '',
    'Unable to upload files!' => '',
    'Users' => '',
    'Admin' => 'Rechten',
    'Audit' => 'Audit',
    'Games' => 'Spellen',
    'Gii' => 'Gii',
    'Home' => 'Home',
    'Login' => 'Inloggen',
    'Logout' => 'Uitloggen',
    'Password' => 'Wachtwoord',
    'Save' => 'Opslaan',
    'Send' => 'Versturen',
    'Signup' => 'Registreren',
    'Username' => 'Gebruikersnaam',
    'create it' => 'maak het',
    'reset it' => 'herstel het',
];
