<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action' => '',
    'Admin' => '',
    'Ajax' => '',
    'Apply Time' => '',
    'Auth Key' => '',
    'Avatar' => '',
    'Bcc' => '',
    'Cc' => '',
    'Code' => '',
    'Created' => '',
    'Created At' => '',
    'Created By' => '',
    'Data' => '',
    'Description' => '',
    'Duration' => '',
    'Email' => '',
    'Emailed' => '',
    'Entry ID' => '',
    'Field' => '',
    'File' => '',
    'First Name' => '',
    'From' => '',
    'Hash' => '',
    'Html' => '',
    'ID' => '',
    'Installation' => '',
    'Ip' => '',
    'Is Deleted By Receiver' => '',
    'Is Deleted By Sender' => '',
    'Is New' => '',
    'Last Name' => '',
    'Line' => '',
    'Link' => '',
    'Memory Max' => '',
    'Message' => '',
    'Model' => '',
    'Model ID' => '',
    'Name' => '',
    'New Value' => '',
    'Old Value' => '',
    'Origin' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Profile Image' => '',
    'Receiver ID' => '',
    'Reply' => '',
    'Request Method' => '',
    'Route' => '',
    'Sender ID' => '',
    'Status' => '',
    'Subject' => '',
    'Successful' => '',
    'Text' => '',
    'To' => '',
    'Trace' => '',
    'Type' => '',
    'Updated At' => '',
    'User ID' => '',
    'Username' => '',
    'Version' => '',
];
